-- Insert job categories data
-- 1st level categories (parent_category is NULL)
-- 2nd level categories (parent_category contains parent name)

INSERT INTO "public"."categories" ("category_id", "name", "parent_category", "icon") VALUES
(1, 'IT & Software', NULL, '💻'),
(10, 'Web Development', 'IT & Software', '🌐'),
(11, 'Mobile Development', 'IT & Software', '📱'),
(12, 'Backend Development', 'IT & Software', '⚙️'),
(13, 'Frontend Development', 'IT & Software', '🎨'),
(14, 'Full Stack Development', 'IT & Software', '🔧'),
(15, 'DevOps & Cloud', 'IT & Software', '☁️'),
(16, 'Data Science & Analytics', 'IT & Software', '📊'),
(17, 'AI & Machine Learning', 'IT & Software', '🤖'),
(18, 'QA & Testing', 'IT & Software', '🧪'),
(19, 'IT Support & Helpdesk', 'IT & Software', '🛠️'),
(20, 'Network & Security', 'IT & Software', '🔒'),
(21, 'Database Administration', 'IT & Software', '🗄️'),
(22, 'UI/UX Design', 'IT & Software', '✨'),
(100, 'Marketing & Sales', NULL, '📈'),
(110, 'Digital Marketing', 'Marketing & Sales', '💡'),
(111, 'Social Media Marketing', 'Marketing & Sales', '📱'),
(112, 'Content Marketing', 'Marketing & Sales', '✍️'),
(113, 'SEO/SEM', 'Marketing & Sales', '🔍'),
(114, 'Email Marketing', 'Marketing & Sales', '📧'),
(115, 'Brand Management', 'Marketing & Sales', '🏷️'),
(116, 'Product Marketing', 'Marketing & Sales', '📦'),
(117, 'Sales Executive', 'Marketing & Sales', '💼'),
(118, 'Business Development', 'Marketing & Sales', '🚀'),
(119, 'Account Management', 'Marketing & Sales', '🤝'),
(120, 'Retail Sales', 'Marketing & Sales', '🏪'),
(200, 'Design & Creative', NULL, '🎨'),
(210, 'Graphic Design', 'Design & Creative', '🖌️'),
(211, 'Product Design', 'Design & Creative', '📐'),
(212, 'Interior Design', 'Design & Creative', '🏠'),
(213, 'Fashion Design', 'Design & Creative', '👗'),
(214, 'Video Editing', 'Design & Creative', '🎬'),
(215, 'Photography', 'Design & Creative', '📷'),
(216, 'Animation & 3D', 'Design & Creative', '🎞️'),
(217, 'Illustration', 'Design & Creative', '🎭'),
(300, 'Customer Service', NULL, '🎧'),
(310, 'Call Center', 'Customer Service', '📞'),
(311, 'Customer Support', 'Customer Service', '💬'),
(312, 'Technical Support', 'Customer Service', '🔧'),
(313, 'Customer Success', 'Customer Service', '⭐'),
(314, 'Front Office', 'Customer Service', '🏢'),
(315, 'Receptionist', 'Customer Service', '📋'),
(400, 'Finance & Accounting', NULL, '💰'),
(410, 'Accounting', 'Finance & Accounting', '📊'),
(411, 'Tax Accounting', 'Finance & Accounting', '🧾'),
(412, 'Auditing', 'Finance & Accounting', '🔍'),
(413, 'Financial Analysis', 'Finance & Accounting', '📈'),
(414, 'Investment Banking', 'Finance & Accounting', '🏦'),
(415, 'Treasury', 'Finance & Accounting', '💵'),
(416, 'Billing & Collections', 'Finance & Accounting', '💳'),
(500, 'Human Resources', NULL, '👥'),
(510, 'Recruitment', 'Human Resources', '🔎'),
(511, 'HR Generalist', 'Human Resources', '📝'),
(512, 'Training & Development', 'Human Resources', '📚'),
(513, 'Compensation & Benefits', 'Human Resources', '💼'),
(514, 'Employee Relations', 'Human Resources', '🤝'),
(515, 'HR Analytics', 'Human Resources', '📊'),
(600, 'Education & Training', NULL, '📚'),
(610, 'Teacher', 'Education & Training', '👨‍🏫'),
(611, 'Tutor', 'Education & Training', '📖'),
(612, 'Instructor', 'Education & Training', '🎓'),
(613, 'Corporate Trainer', 'Education & Training', '💼'),
(614, 'Curriculum Developer', 'Education & Training', '📋'),
(615, 'Educational Consultant', 'Education & Training', '🎯'),
(700, 'Healthcare & Medical', NULL, '⚕️'),
(710, 'Doctor', 'Healthcare & Medical', '👨‍⚕️'),
(711, 'Nurse', 'Healthcare & Medical', '👩‍⚕️'),
(712, 'Pharmacist', 'Healthcare & Medical', '💊'),
(713, 'Medical Technician', 'Healthcare & Medical', '🔬'),
(714, 'Dentist', 'Healthcare & Medical', '🦷'),
(715, 'Physical Therapist', 'Healthcare & Medical', '🏃'),
(716, 'Nutritionist', 'Healthcare & Medical', '🥗'),
(717, 'Medical Representative', 'Healthcare & Medical', '💼'),
(800, 'Engineering', NULL, '⚙️'),
(810, 'Civil Engineering', 'Engineering', '🏗️'),
(811, 'Mechanical Engineering', 'Engineering', '🔧'),
(812, 'Electrical Engineering', 'Engineering', '⚡'),
(813, 'Chemical Engineering', 'Engineering', '🧪'),
(814, 'Industrial Engineering', 'Engineering', '🏭'),
(815, 'Environmental Engineering', 'Engineering', '🌱'),
(816, 'Quality Engineering', 'Engineering', '✅'),
(900, 'Manufacturing & Production', NULL, '🏭'),
(910, 'Production Manager', 'Manufacturing & Production', '👨‍💼'),
(911, 'Production Operator', 'Manufacturing & Production', '👷'),
(912, 'Quality Control', 'Manufacturing & Production', '🔍'),
(913, 'Assembly Line Worker', 'Manufacturing & Production', '🔧'),
(914, 'Machine Operator', 'Manufacturing & Production', '⚙️'),
(915, 'Warehouse Manager', 'Manufacturing & Production', '📦'),
(1000, 'Logistics & Supply Chain', NULL, '🚚'),
(1010, 'Supply Chain Manager', 'Logistics & Supply Chain', '📊'),
(1011, 'Procurement', 'Logistics & Supply Chain', '🛒'),
(1012, 'Inventory Management', 'Logistics & Supply Chain', '📋'),
(1013, 'Shipping & Receiving', 'Logistics & Supply Chain', '📦'),
(1014, 'Courier & Delivery', 'Logistics & Supply Chain', '🚗'),
(1015, 'Import/Export', 'Logistics & Supply Chain', '🌏'),
(1100, 'Hospitality & Food Service', NULL, '🍽️'),
(1110, 'Chef', 'Hospitality & Food Service', '👨‍🍳'),
(1111, 'Cook', 'Hospitality & Food Service', '🍳'),
(1112, 'Waiter/Waitress', 'Hospitality & Food Service', '🍷'),
(1113, 'Bartender', 'Hospitality & Food Service', '🍹'),
(1114, 'Hotel Management', 'Hospitality & Food Service', '🏨'),
(1115, 'Housekeeping', 'Hospitality & Food Service', '🧹'),
(1116, 'Food & Beverage Manager', 'Hospitality & Food Service', '🍴'),
(1117, 'Catering', 'Hospitality & Food Service', '🎂'),
(1200, 'Construction & Architecture', NULL, '🏗️'),
(1210, 'Architect', 'Construction & Architecture', '📐'),
(1211, 'Construction Manager', 'Construction & Architecture', '👷‍♂️'),
(1212, 'Site Engineer', 'Construction & Architecture', '🏗️'),
(1213, 'Surveyor', 'Construction & Architecture', '📏'),
(1214, 'Carpenter', 'Construction & Architecture', '🔨'),
(1215, 'Electrician', 'Construction & Architecture', '💡'),
(1216, 'Plumber', 'Construction & Architecture', '🚰'),
(1217, 'Welder', 'Construction & Architecture', '🔥'),
(1218, 'Bricklayer/Mason', 'Construction & Architecture', '🧱'),
(1219, 'Plasterer', 'Construction & Architecture', '🪛'),
(1220, 'Tile Setter', 'Construction & Architecture', '🔲'),
(1221, 'Painter', 'Construction & Architecture', '🎨'),
(1222, 'Rebar Worker', 'Construction & Architecture', '⚒️'),
(1223, 'Scaffolder', 'Construction & Architecture', '🪜'),
(1224, 'Waterproofing Specialist', 'Construction & Architecture', '💧'),
(1225, 'Glazier', 'Construction & Architecture', '🪟'),
(1226, 'Roofer', 'Construction & Architecture', '🏠'),
(1227, 'Crane Operator', 'Construction & Architecture', '🏗️'),
(1228, 'Heavy Equipment Operator', 'Construction & Architecture', '🚜'),
(1300, 'Legal & Compliance', NULL, '⚖️'),
(1310, 'Lawyer', 'Legal & Compliance', '👨‍⚖️'),
(1311, 'Legal Advisor', 'Legal & Compliance', '📜'),
(1312, 'Paralegal', 'Legal & Compliance', '📋'),
(1313, 'Compliance Officer', 'Legal & Compliance', '✅'),
(1314, 'Contract Manager', 'Legal & Compliance', '📄'),
(1400, 'Media & Communications', NULL, '📺'),
(1410, 'Journalist', 'Media & Communications', '📰'),
(1411, 'Content Writer', 'Media & Communications', '✍️'),
(1412, 'Copywriter', 'Media & Communications', '📝'),
(1413, 'Public Relations', 'Media & Communications', '📢'),
(1414, 'Communications Manager', 'Media & Communications', '📡'),
(1415, 'Broadcaster', 'Media & Communications', '🎙️'),
(1416, 'Editor', 'Media & Communications', '✏️'),
(1500, 'Administrative & Office Support', NULL, '📁'),
(1510, 'Administrative Assistant', 'Administrative & Office Support', '📋'),
(1511, 'Office Manager', 'Administrative & Office Support', '🏢'),
(1512, 'Secretary', 'Administrative & Office Support', '💼'),
(1513, 'Data Entry', 'Administrative & Office Support', '⌨️'),
(1514, 'Document Controller', 'Administrative & Office Support', '📄'),
(1515, 'Personal Assistant', 'Administrative & Office Support', '👔'),
(1600, 'Agriculture & Farming', NULL, '🌾'),
(1610, 'Farm Manager', 'Agriculture & Farming', '🚜'),
(1611, 'Agricultural Engineer', 'Agriculture & Farming', '🌱'),
(1612, 'Plantation Worker', 'Agriculture & Farming', '🌴'),
(1613, 'Livestock Manager', 'Agriculture & Farming', '🐄'),
(1614, 'Fishery', 'Agriculture & Farming', '🐟'),
(1700, 'Others', NULL, '📌'),
(1710, 'Driver', 'Others', '🚗'),
(1711, 'Security Guard', 'Others', '🛡️'),
(1712, 'Cleaning Service', 'Others', '🧹'),
(1713, 'General Labor', 'Others', '💪'),
(1714, 'Part-time Jobs', 'Others', '⏰'),
(1715, 'Freelance', 'Others', '💼')
ON CONFLICT (category_id) DO NOTHING;
